
import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class RecordedSimulation extends Simulation {
    val httpProtocol = http
            .baseUrl( """http://localhost:8080""" )
            .inferHtmlResources()
            .acceptHeader( """text/html,application/xhtml+xml,application/xml,application/json;q=0.9,*/*;q=0.8""" )
            .acceptEncodingHeader( """gzip, deflate""" )
            .acceptLanguageHeader( """en-US,en;q=0.5""" )
            //.userAgentHeader( """Mozilla/5.0 (Macintosh; Intel Mac""" )

    val uri = "http://localhost:8080"

    val scn = scenario( """RecordedSimulation""" )
            .exec( http( """request_1""" ).get( """/game""" ) )
            .exec( http( """request_2""" ).post( """/initGame""" ) )
            .exec( http( """request_3""" ).post( """/addPlayer""" ).body( StringBody( """{"playerColor":"Green","name":"Vince"}""" ) ) )
            .exec( http( """request_4""" ).post( """/addPlayer""" ).body( StringBody( """{"playerColor":"Blue","name":"Paul"}""" ) ) )
            .exec( http( """request_5""" ).post( """/addPlayer""" ).body( StringBody( """{"playerColor":"Red","name":"Tom"}""" ) ) )
            .exec( http( """request_6""" ).post( """/setInitBeginnerState""" ) )
            .exec( http( """request_7""" ).post( """/diceOutBeginner""" ) )
            .exec( http( """request_8""" ).post( """/diceOutBeginner""" ) )
            .exec( http( """request_9""" ).post( """/setBeginner""" ) )
            .exec( http( """request_10""" ).post( """/buildInitSettlement""" ).body( StringBody( """13""" ) ) )
            .exec( http( """request_11""" ).post( """/buildInitRoad""" ).body( StringBody( """21""" ) ) )
            .exec( http( """request_12""" ).post( """/buildInitSettlement""" ).body( StringBody( """31""" ) ) )
            .exec( http( """request_13""" ).post( """/buildInitRoad""" ).body( StringBody( """49""" ) ) )
            .exec( http( """request_14""" ).post( """/buildInitSettlement""" ).body( StringBody( """29""" ) ) )
            .exec( http( """request_15""" ).post( """/buildInitRoad""" ).body( StringBody( """46""" ) ) )
            .exec( http( """request_16""" ).post( """/buildInitSettlement""" ).body( StringBody( """34""" ) ) )
            .exec( http( """request_17""" ).post( """/buildInitRoad""" ).body( StringBody( """54""" ) ) )
            .exec( http( """request_18""" ).post( """/buildInitSettlement""" ).body( StringBody( """43""" ) ) )
            .exec( http( """request_19""" ).post( """/buildInitRoad""" ).body( StringBody( """68""" ) ) )
            .exec( http( """request_20""" ).post( """/buildInitSettlement""" ).body( StringBody( """39""" ) ) )
            .exec( http( """request_21""" ).post( """/buildInitRoad""" ).body( StringBody( """63""" ) ) )
            .exec( http( """request_22""" ).post( """/startTurn""" ) )
            .exec( http( """request_23""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_24""" ).post( """/setPlayerTradeState""" ).body( StringBody( """{"give":[["Clay",1],["Sheep",0],["Wheat",0],["Ore",0],["Wood",0]],"get":[["Clay",0],["Sheep",0],["Wheat",0],["Ore",0],["Wood",1]]}""" ) ) )
            .exec( http( """request_25""" ).post( """/playerTradeDecision""" ).body( StringBody( """true""" ) ) )
            .exec( http( """request_26""" ).post( """/playerTrade""" ).body( StringBody( """{"id":0}""" ) ) )
            .exec( http( """request_27""" ).post( """/endTurn""" ) )
            .exec( http( """request_28""" ).post( """/startTurn""" ) )
            .exec( http( """request_29""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_30""" ).post( """/setPlayerTradeState""" ).body( StringBody( """{"give":[["Clay",0],["Sheep",1],["Wheat",0],["Ore",0],["Wood",0]],"get":[["Clay",0],["Sheep",0],["Wheat",0],["Ore",0],["Wood",1]]}""" ) ) )
            .exec( http( """request_31""" ).post( """/playerTradeDecision""" ).body( StringBody( """true""" ) ) )
            .exec( http( """request_32""" ).post( """/playerTrade""" ).body( StringBody( """{"id":1}""" ) ) )
            .exec( http( """request_33""" ).post( """/setBuildState""" ).body( StringBody( """"Road"""" ) ) )
            .exec( http( """request_34""" ).post( """/build""" ).body( StringBody( """82""" ) ) )
            .exec( http( """request_35""" ).post( """/endTurn""" ) )
            .exec( http( """request_36""" ).post( """/startTurn""" ) )
            .exec( http( """request_37""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_38""" ).post( """/endTurn""" ) )
            .exec( http( """request_39""" ).post( """/startTurn""" ) )
            .exec( http( """request_40""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_41""" ).post( """/endTurn""" ) )
            .exec( http( """request_42""" ).post( """/startTurn""" ) )
            .exec( http( """request_43""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_44""" ).post( """/bankTrade""" ).body( StringBody( """{"give":[["Clay",0],["Sheep",4],["Wheat",0],["Ore",0],["Wood",0]],"get":[["Clay",0],["Sheep",0],["Wheat",0],["Ore",1],["Wood",0]]}""" ) ) )
            .exec( http( """request_45""" ).post( """/endTurn""" ) )
            .exec( http( """request_46""" ).post( """/startTurn""" ) )
            .exec( http( """request_47""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_48""" ).post( """/endTurn""" ) )
            .exec( http( """request_49""" ).post( """/startTurn""" ) )
            .exec( http( """request_50""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_51""" ).post( """/setPlayerTradeState""" ).body( StringBody( """{"give":[["Clay",0],["Sheep",1],["Wheat",0],["Ore",0],["Wood",0]],"get":[["Clay",0],["Sheep",0],["Wheat",0],["Ore",1],["Wood",0]]}""" ) ) )
            .exec( http( """request_52""" ).post( """/playerTradeDecision""" ).body( StringBody( """true""" ) ) )
            .exec( http( """request_53""" ).post( """/playerTrade""" ).body( StringBody( """{"id":2}""" ) ) )
            .exec( http( """request_54""" ).post( """/buyDevCard""" ) )
            .exec( http( """request_55""" ).post( """/endTurn""" ) )
            .exec( http( """request_56""" ).post( """/startTurn""" ) )
            .exec( http( """request_57""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_58""" ).post( """/endTurn""" ) )
            .exec( http( """request_59""" ).post( """/startTurn""" ) )
            .exec( http( """request_60""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_61""" ).post( """/placeRobber""" ).body( StringBody( """31""" ) ) )
            .exec( http( """request_62""" ).post( """/setBuildState""" ).body( StringBody( """"Road"""" ) ) )
            .exec( http( """request_63""" ).post( """/build""" ).body( StringBody( """56""" ) ) )
            .exec( http( """request_64""" ).post( """/setPlayerTradeState""" ).body( StringBody( """{"give":[["Clay",0],["Sheep",0],["Wheat",0],["Ore",0],["Wood",1]],"get":[["Clay",0],["Sheep",0],["Wheat",1],["Ore",0],["Wood",0]]}""" ) ) )
            .exec( http( """request_65""" ).post( """/playerTradeDecision""" ).body( StringBody( """true""" ) ) )
            .exec( http( """request_66""" ).post( """/playerTrade""" ).body( StringBody( """{"id":1}""" ) ) )
            .exec( http( """request_67""" ).post( """/setBuildState""" ).body( StringBody( """"Settlement"""" ) ) )
            .exec( http( """request_68""" ).post( """/build""" ).body( StringBody( """36""" ) ) )
            .exec( http( """request_69""" ).post( """/endTurn""" ) )
            .exec( http( """request_70""" ).post( """/startTurn""" ) )
            .exec( http( """request_71""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_72""" ).post( """/endTurn""" ) )
            .exec( http( """request_73""" ).post( """/startTurn""" ) )
            .exec( http( """request_74""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_75""" ).post( """/endTurn""" ) )
            .exec( http( """request_76""" ).post( """/startTurn""" ) )
            .exec( http( """request_77""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_78""" ).post( """/endTurn""" ) )
            .exec( http( """request_79""" ).post( """/startTurn""" ) )
            .exec( http( """request_80""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_81""" ).post( """/setBuildState""" ).body( StringBody( """"Road"""" ) ) )
            .exec( http( """request_82""" ).post( """/build""" ).body( StringBody( """22""" ) ) )
            .exec( http( """request_83""" ).post( """/endTurn""" ) )
            .exec( http( """request_84""" ).post( """/startTurn""" ) )
            .exec( http( """request_85""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_86""" ).post( """/placeRobber""" ).body( StringBody( """24""" ) ) )
            .exec( http( """request_87""" ).post( """/robberStealFromPlayer""" ).body( StringBody( """{"id":0}""" ) ) )
            .exec( http( """request_88""" ).post( """/setPlayerTradeState""" ).body( StringBody( """{"give":[["Clay",1],["Sheep",0],["Wheat",0],["Ore",0],["Wood",0]],"get":[["Clay",0],["Sheep",0],["Wheat",0],["Ore",1],["Wood",0]]}""" ) ) )
            .exec( http( """request_89""" ).post( """/abortPlayerTrade""" ) )
            .exec( http( """request_90""" ).post( """/endTurn""" ) )
            .exec( http( """request_91""" ).post( """/startTurn""" ) )
            .exec( http( """request_92""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_93""" ).post( """/placeRobber""" ).body( StringBody( """31""" ) ) )
            .exec( http( """request_94""" ).post( """/endTurn""" ) )
            .exec( http( """request_95""" ).post( """/startTurn""" ) )
            .exec( http( """request_96""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_97""" ).post( """/useDevCard""" ).body( StringBody( """"Knight"""" ) ) )
            .exec( http( """request_98""" ).post( """/placeRobber""" ).body( StringBody( """26""" ) ) )
            .exec( http( """request_99""" ).post( """/robberStealFromPlayer""" ).body( StringBody( """{"id":0}""" ) ) )
            .exec( http( """request_100""" ).post( """/endTurn""" ) )
            .exec( http( """request_101""" ).post( """/startTurn""" ) )
            .exec( http( """request_102""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_103""" ).post( """/endTurn""" ) )
            .exec( http( """request_104""" ).post( """/startTurn""" ) )
            .exec( http( """request_105""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_106""" ).post( """/endTurn""" ) )
            .exec( http( """request_107""" ).post( """/startTurn""" ) )
            .exec( http( """request_108""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_109""" ).post( """/endTurn""" ) )
            .exec( http( """request_110""" ).post( """/startTurn""" ) )
            .exec( http( """request_111""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_112""" ).post( """/bankTrade""" ).body( StringBody( """{"give":[["Clay",4],["Sheep",0],["Wheat",0],["Ore",0],["Wood",0]],"get":[["Clay",0],["Sheep",0],["Wheat",0],["Ore",1],["Wood",0]]}""" ) ) )
            .exec( http( """request_113""" ).post( """/setPlayerTradeState""" ).body( StringBody( """{"give":[["Clay",0],["Sheep",1],["Wheat",0],["Ore",0],["Wood",0]],"get":[["Clay",0],["Sheep",0],["Wheat",1],["Ore",0],["Wood",0]]}""" ) ) )
            .exec( http( """request_114""" ).post( """/playerTradeDecision""" ).body( StringBody( """true""" ) ) )
            .exec( http( """request_115""" ).post( """/playerTradeDecision""" ).body( StringBody( """true""" ) ) )
            .exec( http( """request_116""" ).post( """/playerTrade""" ).body( StringBody( """{"id":1}""" ) ) )
            .exec( http( """request_117""" ).post( """/setBuildState""" ).body( StringBody( """"City"""" ) ) )
            .exec( http( """request_118""" ).post( """/build""" ).body( StringBody( """43""" ) ) )
            .exec( http( """request_119""" ).post( """/endTurn""" ) )
            .exec( http( """request_120""" ).post( """/startTurn""" ) )
            .exec( http( """request_121""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_122""" ).post( """/endTurn""" ) )
            .exec( http( """request_123""" ).post( """/startTurn""" ) )
            .exec( http( """request_124""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_125""" ).post( """/endTurn""" ) )
            .exec( http( """request_126""" ).post( """/startTurn""" ) )
            .exec( http( """request_127""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_128""" ).post( """/setPlayerTradeState""" ).body( StringBody( """{"give":[["Clay",0],["Sheep",1],["Wheat",0],["Ore",0],["Wood",0]],"get":[["Clay",1],["Sheep",0],["Wheat",0],["Ore",0],["Wood",1]]}""" ) ) )
            .exec( http( """request_129""" ).post( """/abortPlayerTrade""" ) )
            .exec( http( """request_130""" ).post( """/endTurn""" ) )
            .exec( http( """request_131""" ).post( """/startTurn""" ) )
            .exec( http( """request_132""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_133""" ).post( """/placeRobber""" ).body( StringBody( """31""" ) ) )
            .exec( http( """request_134""" ).post( """/endTurn""" ) )
            .exec( http( """request_135""" ).post( """/startTurn""" ) )
            .exec( http( """request_136""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_137""" ).post( """/placeRobber""" ).body( StringBody( """26""" ) ) )
            .exec( http( """request_138""" ).post( """/robberStealFromPlayer""" ).body( StringBody( """{"id":2}""" ) ) )
            .exec( http( """request_139""" ).post( """/endTurn""" ) )
            .exec( http( """request_140""" ).post( """/startTurn""" ) )
            .exec( http( """request_141""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_142""" ).post( """/endTurn""" ) )
            .exec( http( """request_143""" ).post( """/startTurn""" ) )
            .exec( http( """request_144""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_145""" ).post( """/endTurn""" ) )
            .exec( http( """request_146""" ).post( """/startTurn""" ) )
            .exec( http( """request_147""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_148""" ).post( """/endTurn""" ) )
            .exec( http( """request_149""" ).post( """/startTurn""" ) )
            .exec( http( """request_150""" ).post( """/rollTheDices""" ) )
            .exec( http( """request_151""" ).post( """/dropResourceCardsToRobber""" ).body( StringBody( """[["Clay",0],["Sheep",2],["Wheat",2],["Ore",0],["Wood",0]]""" ) ) )

    setUp( scn.inject( atOnceUsers( 1 ) ) ).protocols( httpProtocol )
}
